### ISSUE TITLE
Broken hyperlinks in latest custom component doc

### ISSUE THREAD

**Issue by djkero** [c16s8/godot-game-settings-docs#2]
There's an issue with these hyperlinks where they should be linking to something like `components.md#Apply-Button` or something similar I guess?:
https://github.com/PunchablePlushie/godot-game-settings-docs/blob/8453484ca49db208daee88c1ac9fe5dd180997e9/src/32/custom_components.md?plain=1#L47

https://github.com/PunchablePlushie/godot-game-settings-docs/blob/8453484ca49db208daee88c1ac9fe5dd180997e9/src/32/custom_components.md?plain=1#L53

**Comment by zijcht** [comment]
Should be fixed in #4.

**Comment by djkero** [comment]
It's not fixed in #4. You need to update the custom_components.md

Change `[Apply Button](4_components/#Apply-Button)` to `[Apply Button](components.md#Apply-Button)`
Change `[Reset Button](4_components/#Reset-Button)` to `[Reset Button](components.md#Reset-Button)`

Don't know if the syntax is correct, but the change should be something similar to that, hah
