### ISSUE TITLE
Broken hyperlink in 3.1 settings

### ISSUE THREAD

**Issue by djkero** [c16s8/godot-game-settings-docs#3]
This link is pointing to `input_setting.md` while the file is named `input.md`
https://github.com/PunchablePlushie/godot-game-settings-docs/blob/8453484ca49db208daee88c1ac9fe5dd180997e9/src/31/settings/settings.md?plain=1#L7

**Comment by zijcht** [comment]
Should be fixed in #4.

**Comment by djkero** [comment]
> Should be fixed in #4.

Yeah this is resolved.
